parking_customer:
    resource: "@ParkingBundle/Resources/config/routing/customer.yml"
    prefix:   /customer

parking_reservation:
    resource: "@ParkingBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation
    
parking_parking:
    resource: "@ParkingBundle/Resources/config/routing/parking.yml"
    prefix:   /parking