parking_customer:
    resource: "@ParkingBundle/Resources/config/routing/customer.yml"
    prefix:   /customer

parking_customer:
    resource: "@ParkingBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

parking_homepage:
    path:     /parking
    defaults: { _controller: ParkingBundle:Default:index }

parking_getAll:
    path:   /parking
    defaults: { _controller: ParkingBundle:Default:getAll }
    methods: GET

parking_get:
    path:   /parking/{id}
    defaults: { _controller: ParkingBundle:Default:get }
    methods: GET