parking_customer:
    resource: "@ParkingBundle/Resources/config/routing/customer.yml"
    prefix:   /customer

parking_homepage:
    path:     /parking
    defaults: { _controller: ParkingBundle:Default:index }
