api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

parking:
    resource: "@ParkingBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation