customer_index:
    path:     /
    defaults: { _controller: "ParkingBundle:Customer:index" }
    methods:  GET

customer_show:
    path:     /show/{id}
    defaults: { _controller: "ParkingBundle:Customer:show" }
    methods:  GET

customer_new:
    path:     /new
    defaults: { _controller: "ParkingBundle:Customer:new" }
    methods:  [GET, POST]

customer_edit:
    path:     /edit/{id}
    defaults: { _controller: "ParkingBundle:Customer:edit" }
    methods:  [GET, POST]

customer_delete:
    path:     /delete/{id}
    defaults: { _controller: "ParkingBundle:Customer:delete" }
    methods:  DELETE
