parking_index:
    path:     /
    defaults: { _controller: "ParkingBundle:Parking:index" }
    methods:  GET

parking_show:
    path:     /show/{id}
    defaults: { _controller: "ParkingBundle:Parking:show" }
    methods:  GET

parking_new:
    path:     /new
    defaults: { _controller: "ParkingBundle:Parking:new" }
    methods:  [GET, POST]

parking_edit:
    path:     /edit/{id}
    defaults: { _controller: "ParkingBundle:Parking:edit" }
    methods:  [GET, POST]

parking_delete:
    path:     /delete/{id}
    defaults: { _controller: "ParkingBundle:Parking:delete" }
    methods:  DELETE
