parkingtype_index:
    path:     /
    defaults: { _controller: "ParkingBundle:ParkingType:index" }
    methods:  GET

parkingtype_show:
    path:     /{id}/show
    defaults: { _controller: "ParkingBundle:ParkingType:show" }
    methods:  GET

parkingtype_new:
    path:     /new
    defaults: { _controller: "ParkingBundle:ParkingType:new" }
    methods:  [GET, POST]

parkingtype_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParkingBundle:ParkingType:edit" }
    methods:  [GET, POST]

parkingtype_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParkingBundle:ParkingType:delete" }
    methods:  DELETE
