parking_reservation_index:
    path:     /
    defaults: { _controller: "ParkingBundle:Reservation:index" }
    methods:  GET

parking_reservation_show:
    path:     /{id}/show
    defaults: { _controller: "ParkingBundle:Reservation:show" }
    methods:  GET

parking_reservation_new:
    path:     /new
    defaults: { _controller: "ParkingBundle:Reservation:new" }
    methods:  [GET, POST]

parking_reservation_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParkingBundle:Reservation:edit" }
    methods:  [GET, POST]

parking_reservation_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParkingBundle:Reservation:delete" }
    methods:  DELETE
